# Generated by Django 5.2.16 on 2026-08-01 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='token',
            field=models.CharField(default='b8bc55df77e34f48bdd1e2852da0fabc', max_length=64, unique=True),
        ),
    ]
