# Generated by Django 5.2.16 on 2026-08-02 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_checksum_document_pages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='keywords',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='reading_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
